version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/infra/docker"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      docker-images:
        patterns:
          - "*"
  - package-ecosystem: "composer"
    directories:
      - "/apps/operations"
      - "/apps/tracking"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      composer-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      npm-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/setup"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      github-actions:
        patterns:
          - "*"
