import { StyleSheet } from 'react-native';

/** Layout shared by the fuel controls. Colors come from the theme inline. */
export const fuelStyles = StyleSheet.create({
    button: {
        minHeight: 52,
        minWidth: 56,
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    buttonRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    field: { gap: 8 },
    input: {
        minHeight: 52,
        borderRadius: 10,
        padding: 14,
        fontSize: 16,
    },
    inlineRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    row: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    section: { gap: 18, paddingVertical: 18 },
    title: { fontSize: 20, fontWeight: '700' },
    body: { fontSize: 14, lineHeight: 21 },
    banner: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 12,
        padding: 14,
        borderRadius: 12,
        borderLeftWidth: 4,
    },
    card: {
        borderRadius: 14,
        borderWidth: 1,
        padding: 16,
        gap: 10,
    },
    pill: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        alignSelf: 'stretch',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 8,
    },
    dot: { width: 8, height: 8, borderRadius: 4 },
    pickerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        minHeight: 60,
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 12,
    },
    sheetBackdrop: {
        flex: 1,
    },
    scrim: {
        bottom: 0,
        left: 0,
        opacity: 0.45,
        position: 'absolute',
        right: 0,
        top: 0,
    },
    sheet: {
        maxHeight: '75%',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        padding: 16,
        paddingBottom: 28,
        gap: 12,
    },
    sheetHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    iconButton: {
        width: 48,
        height: 48,
        alignItems: 'center',
        justifyContent: 'center',
    },
    radio: {
        width: 22,
        height: 22,
        borderRadius: 11,
        borderWidth: 2,
        alignItems: 'center',
        justifyContent: 'center',
    },
    radioInner: { width: 10, height: 10, borderRadius: 5 },
    unitRow: {
        flexDirection: 'row',
        alignItems: 'center',
        minHeight: 52,
        borderRadius: 10,
        overflow: 'hidden',
    },
    unitInput: { flex: 1, paddingHorizontal: 14, fontSize: 17, minHeight: 50 },
    unitBox: {
        alignSelf: 'stretch',
        minWidth: 52,
        alignItems: 'center',
        justifyContent: 'center',
        borderLeftWidth: 1,
    },
    segmented: {
        flexDirection: 'row',
        borderWidth: 1,
        borderRadius: 10,
        overflow: 'hidden',
    },
    segment: {
        flex: 1,
        minHeight: 48,
        alignItems: 'center',
        justifyContent: 'center',
    },
    radioCard: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        minHeight: 52,
        paddingHorizontal: 14,
        borderRadius: 12,
    },
});
