// Demonstration duty history. HosScreen uses TIMELINE_HISTORY_DAYS as the
// default `timelineHistory` when no server history is passed in.
import type { ShiftLogEvent, TimelineDayHistory } from './hos-types';

export const INITIAL_LOG_EVENTS: ShiftLogEvent[] = [
    {
        id: 'log-1',
        status: 'driving',
        startTime: '08:00 AM',
        endTime: '09:30 AM',
        durationFormatted: '1h 30m',
        details: 'Transit via Port Access Highway with 50T Mobile Crane',
        location: 'Manila North Harbor Corridor',
    },
    {
        id: 'log-2',
        status: 'operating',
        startTime: '09:30 AM',
        endTime: '12:00 PM',
        durationFormatted: '2h 30m',
        details: 'Outriggers deployed, foundation steel rebar tandem lifts',
        location: 'Block 4 Tower Site, Taguig',
    },
    {
        id: 'log-3',
        status: 'on_break',
        startTime: '12:00 PM',
        endTime: '12:30 PM',
        durationFormatted: '0h 30m',
        details: 'Mandatory midday meal & rest period',
        location: 'Site Welfare Area',
    },
    {
        id: 'log-4',
        status: 'operating',
        startTime: '12:30 PM',
        endTime: 'Current',
        durationFormatted: '1h 30m',
        details: 'Structural pre-cast slab placement in progress',
        location: 'Block 4 Tower Site, Taguig',
    },
];

export const TIMELINE_HISTORY_DAYS: TimelineDayHistory[] = [
    {
        id: 'day-0',
        dayLabel: 'Today (Sep 5)',
        dateFormatted: 'Friday, Sep 5, 2026',
        shortDate: 'Today',
        isToday: true,
        driveHoursFormatted: '1h 30m',
        onDutyHoursFormatted: '4h 00m',
        offDutyHoursFormatted: '8h 00m',
        totalShiftFormatted: '5h 30m',
        certificationStatus: 'active',
        certifiedByText: 'Sign off and certify log at end of shift',
        segments: {
            off: [{ left: '0%', width: '33.3%' }],
            brk: [{ left: '50%', width: '2.1%' }],
            drv: [{ left: '33.3%', width: '6.2%' }],
            on: [
                { left: '39.5%', width: '10.5%' },
                { left: '52.1%', width: '6.2%' },
            ],
        },
        events: INITIAL_LOG_EVENTS,
    },
    {
        id: 'day-1',
        dayLabel: 'Thu, Sep 4 (Yesterday)',
        dateFormatted: 'Thursday, Sep 4, 2026',
        shortDate: 'Sep 4',
        isToday: false,
        driveHoursFormatted: '6h 15m',
        onDutyHoursFormatted: '3h 00m',
        offDutyHoursFormatted: '14h 45m',
        totalShiftFormatted: '9h 15m',
        certificationStatus: 'certified',
        certifiedByText: '✓ Certified by Alex Rivera · Sep 4, 17:18 PHT',
        segments: {
            off: [
                { left: '0%', width: '29.2%' },
                { left: '70.8%', width: '29.2%' },
            ],
            brk: [{ left: '47.9%', width: '3.1%' }],
            drv: [
                { left: '33.3%', width: '14.6%' },
                { left: '51%', width: '11.5%' },
            ],
            on: [
                { left: '29.2%', width: '4.1%' },
                { left: '62.5%', width: '8.3%' },
            ],
        },
        events: [
            {
                id: 'log-sep4-1',
                status: 'operating',
                startTime: '07:00 AM',
                endTime: '08:00 AM',
                durationFormatted: '1h 00m',
                details:
                    'Pre-trip walkaround, outrigger hydraulic inspection & load chart verify',
                location: 'Depot Yard 2, Manila',
            },
            {
                id: 'log-sep4-2',
                status: 'driving',
                startTime: '08:00 AM',
                endTime: '11:30 AM',
                durationFormatted: '3h 30m',
                details:
                    'Lowbed equipment transit via SLEX to Calamba construction hub',
                location: 'SLEX Southbound Km 42',
            },
            {
                id: 'log-sep4-3',
                status: 'on_break',
                startTime: '11:30 AM',
                endTime: '12:15 PM',
                durationFormatted: '0h 45m',
                details: 'Mandatory mid-shift driver meal & thermal break',
                location: 'Calamba Oasis Station',
            },
            {
                id: 'log-sep4-4',
                status: 'driving',
                startTime: '12:15 PM',
                endTime: '03:00 PM',
                durationFormatted: '2h 45m',
                details: 'Equipment transit to Batangas Industrial Plant',
                location: 'STAR Tollway Corridor',
            },
            {
                id: 'log-sep4-5',
                status: 'operating',
                startTime: '03:00 PM',
                endTime: '05:00 PM',
                durationFormatted: '2h 00m',
                details:
                    'Equipment placement & post-trip safety checklist audit',
                location: 'Batangas Port Terminal',
            },
            {
                id: 'log-sep4-6',
                status: 'off_duty',
                startTime: '05:00 PM',
                endTime: '11:59 PM',
                durationFormatted: '7h 00m',
                details:
                    'Shift finalized and certified. 10-hour rest clock active.',
                location: 'Driver Rest Lodge',
            },
        ],
    },
    {
        id: 'day-2',
        dayLabel: 'Wed, Sep 3',
        dateFormatted: 'Wednesday, Sep 3, 2026',
        shortDate: 'Sep 3',
        isToday: false,
        driveHoursFormatted: '2h 00m',
        onDutyHoursFormatted: '7h 15m',
        offDutyHoursFormatted: '14h 45m',
        totalShiftFormatted: '9h 15m',
        certificationStatus: 'certified',
        certifiedByText: '✓ Certified by Alex Rivera · Sep 3, 16:42 PHT',
        segments: {
            off: [
                { left: '0%', width: '27.1%' },
                { left: '68.8%', width: '31.2%' },
            ],
            brk: [{ left: '54.2%', width: '3.1%' }],
            drv: [{ left: '33.3%', width: '8.3%' }],
            on: [
                { left: '27.1%', width: '6.2%' },
                { left: '41.6%', width: '12.6%' },
                { left: '57.3%', width: '11.5%' },
            ],
        },
        events: [
            {
                id: 'log-sep3-1',
                status: 'operating',
                startTime: '06:30 AM',
                endTime: '08:00 AM',
                durationFormatted: '1h 30m',
                details:
                    'Safety toolbox briefing and crane wire-rope spooling check',
                location: 'BGC Site A, Taguig',
            },
            {
                id: 'log-sep3-2',
                status: 'driving',
                startTime: '08:00 AM',
                endTime: '10:00 AM',
                durationFormatted: '2h 00m',
                details: 'Transfer mobile crane unit to Tower 2 Crane Pad',
                location: 'BGC Metro Corridor',
            },
            {
                id: 'log-sep3-3',
                status: 'operating',
                startTime: '10:00 AM',
                endTime: '01:00 PM',
                durationFormatted: '3h 00m',
                details:
                    'Precast beam hoisting and level 12 structural placement',
                location: 'Tower 2 Site Pad',
            },
            {
                id: 'log-sep3-4',
                status: 'on_break',
                startTime: '01:00 PM',
                endTime: '01:45 PM',
                durationFormatted: '0h 45m',
                details: 'Meal pause and hydration break',
                location: 'Site Welfare Quarter',
            },
            {
                id: 'log-sep3-5',
                status: 'operating',
                startTime: '01:45 PM',
                endTime: '04:30 PM',
                durationFormatted: '2h 45m',
                details:
                    'Precision HVAC chiller unit roof lift and outrigger stowage',
                location: 'Tower 2 Rooftop Pad',
            },
        ],
    },
    {
        id: 'day-3',
        dayLabel: 'Tue, Sep 2',
        dateFormatted: 'Tuesday, Sep 2, 2026',
        shortDate: 'Sep 2',
        isToday: false,
        driveHoursFormatted: '8h 00m',
        onDutyHoursFormatted: '1h 00m',
        offDutyHoursFormatted: '15h 00m',
        totalShiftFormatted: '9h 00m',
        certificationStatus: 'certified',
        certifiedByText: '✓ Certified by Alex Rivera · Sep 2, 16:15 PHT',
        segments: {
            off: [
                { left: '0%', width: '25%' },
                { left: '66.7%', width: '33.3%' },
            ],
            brk: [{ left: '47.9%', width: '4.2%' }],
            drv: [
                { left: '29.2%', width: '18.7%' },
                { left: '52.1%', width: '14.6%' },
            ],
            on: [{ left: '25%', width: '4.2%' }],
        },
        events: [
            {
                id: 'log-sep2-1',
                status: 'operating',
                startTime: '06:00 AM',
                endTime: '07:00 AM',
                durationFormatted: '1h 00m',
                details:
                    'Pre-trip equipment inspection, tire pressure and brake line check',
                location: 'Subic Bay Depot',
            },
            {
                id: 'log-sep2-2',
                status: 'driving',
                startTime: '07:00 AM',
                endTime: '11:30 AM',
                durationFormatted: '4h 30m',
                details: 'Long-haul transport via SCTEX & NLEX southward',
                location: 'NLEX Km 65 Northbound',
            },
            {
                id: 'log-sep2-3',
                status: 'on_break',
                startTime: '11:30 AM',
                endTime: '12:30 PM',
                durationFormatted: '1h 00m',
                details: 'Driver lunch and recorded 30-minute break',
                location: 'NLEX Mega Station',
            },
            {
                id: 'log-sep2-4',
                status: 'driving',
                startTime: '12:30 PM',
                endTime: '04:00 PM',
                durationFormatted: '3h 30m',
                details:
                    'Delivery transit to Manila International Container Yard',
                location: 'R-10 Highway Manila',
            },
        ],
    },
    {
        id: 'day-4',
        dayLabel: 'Mon, Sep 1',
        dateFormatted: 'Monday, Sep 1, 2026',
        shortDate: 'Sep 1',
        isToday: false,
        driveHoursFormatted: '0h 00m',
        onDutyHoursFormatted: '0h 00m',
        offDutyHoursFormatted: '24h 00m',
        totalShiftFormatted: '0h 00m',
        certificationStatus: 'restart',
        certifiedByText: '✓ 34-Hour Restart Period · Off Duty Logged',
        segments: {
            off: [{ left: '0%', width: '100%' }],
            brk: [],
            drv: [],
            on: [],
        },
        events: [
            {
                id: 'log-sep1-1',
                status: 'off_duty',
                startTime: '12:00 AM',
                endTime: '11:59 PM',
                durationFormatted: '24h 00m',
                details:
                    'Mandatory 34-Hour HoS Cycle Restart — 24 consecutive hours off-duty',
                location: 'Operator Residence',
            },
        ],
    },
    {
        id: 'day-5',
        dayLabel: 'Sun, Aug 31',
        dateFormatted: 'Sunday, Aug 31, 2026',
        shortDate: 'Aug 31',
        isToday: false,
        driveHoursFormatted: '0h 00m',
        onDutyHoursFormatted: '0h 00m',
        offDutyHoursFormatted: '24h 00m',
        totalShiftFormatted: '0h 00m',
        certificationStatus: 'restart',
        certifiedByText: '✓ 34-Hour Restart Period · Off Duty Logged',
        segments: {
            off: [{ left: '0%', width: '100%' }],
            brk: [],
            drv: [],
            on: [],
        },
        events: [
            {
                id: 'log-aug31-1',
                status: 'off_duty',
                startTime: '12:00 AM',
                endTime: '11:59 PM',
                durationFormatted: '24h 00m',
                details:
                    'Mandatory 34-Hour HoS Cycle Restart — 24 consecutive hours off-duty',
                location: 'Operator Residence',
            },
        ],
    },
    {
        id: 'day-6',
        dayLabel: 'Sat, Aug 30',
        dateFormatted: 'Saturday, Aug 30, 2026',
        shortDate: 'Aug 30',
        isToday: false,
        driveHoursFormatted: '6h 00m',
        onDutyHoursFormatted: '3h 00m',
        offDutyHoursFormatted: '15h 00m',
        totalShiftFormatted: '9h 00m',
        certificationStatus: 'certified',
        certifiedByText: '✓ Certified by Alex Rivera · Aug 30, 17:10 PHT',
        segments: {
            off: [
                { left: '0%', width: '31.2%' },
                { left: '70.8%', width: '29.2%' },
            ],
            brk: [{ left: '52.1%', width: '2.1%' }],
            drv: [
                { left: '37.5%', width: '14.6%' },
                { left: '54.2%', width: '10.4%' },
            ],
            on: [
                { left: '31.2%', width: '6.3%' },
                { left: '64.6%', width: '6.2%' },
            ],
        },
        events: [
            {
                id: 'log-aug30-1',
                status: 'operating',
                startTime: '07:30 AM',
                endTime: '09:00 AM',
                durationFormatted: '1h 30m',
                details:
                    'Boom extension & load moment indicator calibration test',
                location: 'Clark Heavy Depot',
            },
            {
                id: 'log-aug30-2',
                status: 'driving',
                startTime: '09:00 AM',
                endTime: '12:30 PM',
                durationFormatted: '3h 30m',
                details: 'Transit convoy escort to Subic Freeport gate',
                location: 'SCTEX Clark-Subic',
            },
            {
                id: 'log-aug30-3',
                status: 'on_break',
                startTime: '12:30 PM',
                endTime: '01:00 PM',
                durationFormatted: '0h 30m',
                details: 'Midday lunch & mandatory rest',
                location: 'Subic Toll Plaza Rest',
            },
            {
                id: 'log-aug30-4',
                status: 'driving',
                startTime: '01:00 PM',
                endTime: '03:30 PM',
                durationFormatted: '2h 30m',
                details: 'On-site transit to drydock berth 4',
                location: 'Subic Shipyard Zone',
            },
            {
                id: 'log-aug30-5',
                status: 'operating',
                startTime: '03:30 PM',
                endTime: '05:00 PM',
                durationFormatted: '1h 30m',
                details: 'Tandem hoist positioning and outrigger lock',
                location: 'Drydock Berth 4',
            },
        ],
    },
    {
        id: 'day-7',
        dayLabel: 'Fri, Aug 29',
        dateFormatted: 'Friday, Aug 29, 2026',
        shortDate: 'Aug 29',
        isToday: false,
        driveHoursFormatted: '3h 30m',
        onDutyHoursFormatted: '5h 00m',
        offDutyHoursFormatted: '15h 30m',
        totalShiftFormatted: '8h 30m',
        certificationStatus: 'certified',
        certifiedByText: '✓ Certified by Alex Rivera · Aug 29, 16:15 PHT',
        segments: {
            off: [
                { left: '0%', width: '29.2%' },
                { left: '66.7%', width: '33.3%' },
            ],
            brk: [{ left: '50%', width: '3.1%' }],
            drv: [{ left: '35.4%', width: '14.6%' }],
            on: [
                { left: '29.2%', width: '6.2%' },
                { left: '53.1%', width: '13.6%' },
            ],
        },
        events: [
            {
                id: 'log-aug29-1',
                status: 'operating',
                startTime: '07:00 AM',
                endTime: '08:30 AM',
                durationFormatted: '1h 30m',
                details: 'Equipment rigging and outrigger cribbing checks',
                location: 'Clark Freeport Zone',
            },
            {
                id: 'log-aug29-2',
                status: 'driving',
                startTime: '08:30 AM',
                endTime: '12:00 PM',
                durationFormatted: '3h 30m',
                details: 'Highway transit of 50T hydraulic crane',
                location: 'MacArthur Highway',
            },
            {
                id: 'log-aug29-3',
                status: 'on_break',
                startTime: '12:00 PM',
                endTime: '12:45 PM',
                durationFormatted: '0h 45m',
                details: 'Mandatory rest & lunch period',
                location: 'San Fernando Oasis',
            },
            {
                id: 'log-aug29-4',
                status: 'operating',
                startTime: '12:45 PM',
                endTime: '04:00 PM',
                durationFormatted: '3h 15m',
                details:
                    'Bridge girder positioning lifts & post-shift walkaround',
                location: 'Pampanga River Bridge Site',
            },
        ],
    },
];
