import type {
    DvirInspectionRecord,
    TechnicianInspectionCheck,
} from '../../types/index';

// Offline demo history shown before the server history loads.

const DEFAULT_CHECKS: TechnicianInspectionCheck[] = [
    {
        id: 'chk-hyd-01',
        category: 'hydraulics',
        label: 'Hydraulic cylinders, rams & hoses',
        status: 'good',
        statusLabel: 'Pass · No fluid leaks',
        icon: '',
    },
    {
        id: 'chk-elec-01',
        category: 'electrical',
        label: 'Load Moment Indicator (LMI) & A2B Alarm',
        status: 'good',
        statusLabel: 'Pass · Audible alarm active',
        icon: '',
    },
    {
        id: 'chk-struct-01',
        category: 'structural',
        label: 'Telescopic boom & wear pads',
        status: 'good',
        statusLabel: 'Pass · Structural integrity intact',
        icon: '',
    },
    {
        id: 'chk-rope-01',
        category: 'structural',
        label: 'Hoist wire rope, winch & main hook block',
        status: 'good',
        statusLabel: 'Pass · Wire rope & safety latch intact',
        icon: '',
    },
    {
        id: 'chk-tire-01',
        category: 'tires_tracks',
        label: 'Tire pressures & wheel lug torque',
        status: 'good',
        statusLabel: 'Pass · 120 PSI baseline verified',
        icon: '',
    },
    {
        id: 'chk-safe-01',
        category: 'safety_devices',
        label: 'Emergency e-stop, beacon & horn',
        status: 'good',
        statusLabel: 'Pass · Functional',
        icon: '',
    },
];

export const INITIAL_HISTORY: DvirInspectionRecord[] = [
    {
        id: 'DVIR-2026-0831-01',
        type: 'pre_trip',
        assetCode: 'ALB-CRN-050',
        assetName: '50T Tadano All-Terrain Crane',
        inspectorName: 'Alex Rivera (Certified Operator)',
        startingOdometerKm: 42150,
        engineHours: 1842.5,
        hasDefects: false,
        criticalDefectsCount: 0,
        checks: DEFAULT_CHECKS,
        signatureCaptured: true,
        remarks:
            'Today pre-shift inspection passed with zero defects. Outriggers & LMI verified.',
        completedAt: new Date().toISOString(),
    },
    {
        id: 'DVIR-2026-0830-02',
        type: 'post_trip',
        assetCode: 'ALB-CRN-050',
        assetName: '50T Tadano All-Terrain Crane',
        inspectorName: 'Alex Rivera (Certified Operator)',
        endingOdometerKm: 42120,
        engineHours: 1836,
        hasDefects: false,
        criticalDefectsCount: 0,
        checks: DEFAULT_CHECKS,
        signatureCaptured: true,
        remarks: 'Post-job walkaround clean. Asset parked and secured.',
        completedAt: new Date(Date.now() - 86400000).toISOString(),
    },
    {
        id: 'DVIR-2026-0828-01',
        type: 'pre_trip',
        assetCode: 'ALB-CRN-050',
        assetName: '50T Tadano All-Terrain Crane',
        inspectorName: 'Alex Rivera (Certified Operator)',
        startingOdometerKm: 42080,
        engineHours: 1824,
        hasDefects: false,
        criticalDefectsCount: 0,
        checks: DEFAULT_CHECKS,
        signatureCaptured: true,
        remarks: 'Pre-trip complete. Fluid levels verified.',
        completedAt: new Date(Date.now() - 259200000).toISOString(),
    },
    {
        id: 'DVIR-2026-0818-01',
        type: 'post_trip',
        assetCode: 'ALB-CRN-050',
        assetName: '50T Tadano All-Terrain Crane',
        inspectorName: 'Alex Rivera (Certified Operator)',
        endingOdometerKm: 41850,
        engineHours: 1795,
        hasDefects: true,
        criticalDefectsCount: 0,
        checks: DEFAULT_CHECKS,
        signatureCaptured: true,
        remarks: 'Hydraulic hose sweat noted and reported to fleet shop.',
        completedAt: new Date(Date.now() - 1123200000).toISOString(),
    },
];
