import { StyleSheet } from 'react-native';

export const colors = {
    background: '#F1F5F9',
    surface: '#FFFFFF',
    surfaceMuted: '#F1F5F9',
    surfaceElevated: '#FFFFFF',
    surfaceDark: '#0F172A',
    surfaceDarkElevated: '#1E293B',
    text: '#0F172A',
    textSecondary: '#64748B',
    textOnDark: '#FFFFFF',
    secondary: '#64748B',
    muted: '#64748B',
    mutedOnDark: '#94A3B8',
    border: '#E2E8F0',
    borderSubtle: '#F1F5F9',
    borderStrong: '#CBD5E1',
    // Brand & Interactive / Accent (Amber)
    accent: '#D97706',
    accentLight: '#FEF3C7',
    accentSoft: '#FEF3C7',
    accentBorder: '#FDE68A',
    accentDark: '#B45309',
    primary: '#D97706',
    primaryDark: '#B45309',
    primaryLight: '#FEF3C7',
    primarySoft: '#FEF3C7',
    primaryBorder: '#FDE68A',
    amber: '#D97706',
    amberLight: '#FEF3C7',
    amberSoft: '#FEF3C7',
    amberBorder: '#FDE68A',
    amberDark: '#B45309',
    // Warning / Orange
    warning: '#EA580C',
    warningLight: '#FFF7ED',
    warningSoft: '#FFEDD5',
    warningBorder: '#FED7AA',
    warningDark: '#9A3412',
    // Blue / Info
    blue: '#2563EB',
    blueLight: '#EFF6FF',
    blueSoft: '#DBEAFE',
    blueBorder: '#BFDBFE',
    blueDark: '#1D4ED8',
    // Green / Emerald / Success
    green: '#10B981',
    greenLight: '#ECFDF5',
    greenSoft: '#D1FAE5',
    greenBorder: '#A7F3D0',
    greenDark: '#047857',
    // Red / Crimson / Danger
    red: '#EF4444',
    redLight: '#FEF2F2',
    redSoft: '#FEE2E2',
    redBorder: '#FECACA',
    redDark: '#B91C1C',
    // Route & Telemetry HUD Tokens (Dark Mode)
    hudBackground: '#090D16',
    hudSurface: '#1E293B',
    hudSurfaceElevated: '#1E293B',
    hudBorder: '#334155',
    hudBorderSubtle: 'rgba(255, 255, 255, 0.1)',
    hudText: '#F8FAFC',
    hudTextDim: '#94A3B8',
    hudAccent: '#F59E0B',
    hudAmber: '#F59E0B',
    white: '#FFFFFF',
};

export const shadows = {
    sm: {
        shadowColor: '#0f172a',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
        boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04)',
    },
    md: {
        shadowColor: '#0f172a',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.07,
        shadowRadius: 6,
        elevation: 3,
        boxShadow: '0 4px 12px rgba(15, 23, 42, 0.06)',
    },
    lg: {
        shadowColor: '#0f172a',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.1,
        shadowRadius: 16,
        elevation: 6,
        boxShadow: '0 8px 24px rgba(15, 23, 42, 0.09)',
    },
};

export const sharedStyles = StyleSheet.create({
    panel: {
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        ...shadows.md,
    },
    panelTitle: {
        color: colors.text,
        fontSize: 17,
        fontWeight: '700',
        letterSpacing: -0.2,
        marginBottom: 8,
    },
    body: { color: colors.secondary, fontSize: 15, lineHeight: 22 },
    button: {
        minHeight: 48,
        borderRadius: 12,
        paddingHorizontal: 18,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.primary,
        ...shadows.sm,
    },
    buttonText: {
        color: colors.white,
        fontSize: 15,
        fontWeight: '700',
        textAlign: 'center',
        letterSpacing: -0.2,
    },
    input: {
        minHeight: 48,
        borderWidth: 1,
        borderColor: colors.borderStrong,
        borderRadius: 12,
        paddingHorizontal: 14,
        paddingVertical: 12,
        color: colors.text,
        backgroundColor: colors.surface,
        fontSize: 16,
    },
    statusText: { color: colors.secondary, fontSize: 14, lineHeight: 20 },
});
