import { StyleSheet } from 'react-native';

export const colors = {
    background: '#f8fafc',
    surface: '#ffffff',
    surfaceMuted: '#f1f5f9',
    surfaceDark: '#1e293b',
    surfaceDarkElevated: '#334155',
    text: '#172033',
    textOnDark: '#f8fafc',
    secondary: '#475569',
    muted: '#64748b',
    mutedOnDark: '#cbd5e1',
    border: '#cbd5e1',
    amber: '#d97706',
    amberLight: '#fff7ed',
    amberSoft: '#fef3c7',
    amberBorder: '#fde68a',
    amberDark: '#b45309',
    blue: '#1d4ed8',
    blueLight: '#eff6ff',
    blueSoft: '#eff6ff',
    blueBorder: '#bfdbfe',
    blueDark: '#1e3a8a',
    green: '#166534',
    greenLight: '#f0fdf4',
    greenSoft: '#f0fdf4',
    greenBorder: '#bbf7d0',
    greenDark: '#14532d',
    red: '#b91c1c',
    redLight: '#fef2f2',
    redSoft: '#fef2f2',
    redBorder: '#fecaca',
    white: '#ffffff',
};

export const sharedStyles = StyleSheet.create({
    panel: {
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
    },
    panelTitle: {
        color: colors.text,
        fontSize: 18,
        fontWeight: '700',
        marginBottom: 8,
    },
    body: { color: colors.secondary, fontSize: 15, lineHeight: 22 },
    button: {
        minHeight: 48,
        borderRadius: 8,
        paddingHorizontal: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    buttonText: {
        color: colors.white,
        fontSize: 15,
        fontWeight: '700',
        textAlign: 'center',
    },
    input: {
        minHeight: 48,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
        color: colors.text,
        backgroundColor: colors.surface,
        fontSize: 16,
    },
    statusText: { color: colors.secondary, fontSize: 14, lineHeight: 20 },
});
