import { StyleSheet } from 'react-native';

export const colors = {
    background: '#f4f6f8',
    surface: '#ffffff',
    surfaceMuted: '#eef2f6',
    surfaceDark: '#172033',
    surfaceDarkElevated: '#25324a',
    text: '#172033',
    textOnDark: '#ffffff',
    secondary: '#475569',
    muted: '#64748b',
    mutedOnDark: '#cbd5e1',
    border: '#d5dce5',
    borderStrong: '#aeb8c6',
    amber: '#e98a00',
    amberLight: '#fff7ed',
    amberSoft: '#fef3c7',
    amberBorder: '#f7c56b',
    amberDark: '#9a4d00',
    warning: '#c2410c',
    warningLight: '#fff7ed',
    warningSoft: '#ffedd5',
    warningBorder: '#fdba74',
    warningDark: '#7c2d12',
    blue: '#1d4ed8',
    blueLight: '#eff6ff',
    blueSoft: '#dbeafe',
    blueBorder: '#bfdbfe',
    blueDark: '#1e3a8a',
    green: '#166534',
    greenLight: '#f0fdf4',
    greenSoft: '#dcfce7',
    greenBorder: '#bbf7d0',
    greenDark: '#14532d',
    red: '#b91c1c',
    redLight: '#fef2f2',
    redSoft: '#fee2e2',
    redBorder: '#fecaca',
    redDark: '#7f1d1d',
    white: '#ffffff',
};

export const sharedStyles = StyleSheet.create({
    panel: {
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
    },
    panelTitle: {
        color: colors.text,
        fontSize: 18,
        fontWeight: '700',
        marginBottom: 8,
    },
    body: { color: colors.secondary, fontSize: 15, lineHeight: 22 },
    button: {
        minHeight: 48,
        borderRadius: 8,
        paddingHorizontal: 16,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.amber,
    },
    buttonText: {
        color: colors.text,
        fontSize: 15,
        fontWeight: '700',
        textAlign: 'center',
    },
    input: {
        minHeight: 48,
        borderWidth: 1,
        borderColor: colors.borderStrong,
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 12,
        color: colors.text,
        backgroundColor: colors.surface,
        fontSize: 16,
    },
    statusText: { color: colors.secondary, fontSize: 14, lineHeight: 20 },
});
